In [ ]:
#載入執行程式所需套件
import pandas as pd
import numpy as np
from scipy import stats

In [ ]:
#讀取檔案，將檔案名稱設為data
data=pd.read_excel('nba2.xlsx')

In [ ]:
#讀取檔案前五列資料,欄位說明請參考「NBA檔案欄位說明」
data.head()

,DATASET,R/P,DATE,TEAMS,H/R,W/E,W/L,DIFF,1Q,2Q,...,TO,BL,PTS,POSS,PACE,OEFF,DEFF,REST DAYS,OPENING ODDS,SPREAD
0,2016-2017 Regular Season,1,10/25/2016,New York,2,1,0,-29,18,27,...,18,6,88,100.4,100.4,87.7,116.6,3,205.5,9.5
1,2016-2017 Regular Season,1,10/25/2016,Cleveland,1,1,1,29,28,20,...,14,5,117,100.4,100.4,116.6,87.7,3,-9.5,-9.5
2,2016-2017 Regular Season,1,10/25/2016,Utah,2,2,0,-9,26,20,...,11,5,104,92.5,92.5,112.4,122.1,3,194.0,6.0
3,2016-2017 Regular Season,1,10/25/2016,Portland,1,2,1,9,26,28,...,12,3,113,92.5,92.5,122.1,112.4,3,-6.0,-6.0
4,2016-2017 Regular Season,1,10/25/2016,San Antonio,2,2,1,29,31,33,...,13,3,129,98.8,98.8,130.6,101.2,3,210.5,8.0

In [ ]:
#讀取檔案各欄位基本資訊
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2460 entries, 0 to 2459
Data columns (total 43 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   DATASET       2460 non-null   object
 1   R/P           2460 non-null   int64
 2   DATE          2460 non-null   object
 3   TEAMS         2460 non-null   object
 4   H/R           2460 non-null   int64
 5   W/E           2460 non-null   int64
 6   W/L           2460 non-null   int64
 7   DIFF          2460 non-null   int64
 8   1Q            2460 non-null   int64
 9   2Q            2460 non-null   int64
 10  3Q            2460 non-null   int64
 11  4Q            2460 non-null   int64
 12  F             2460 non-null   int64
 13  MIN           2460 non-null   int64
 14  FG            2460 non-null   int64
 15  FGA           2460 non-null   int64
 16  3P            2460 non-null   int64
 17  3PA           2460 non-null   int64
 18  FT            2460 non-null   int64
 19  FTA           2460 non-null   int64
 20  OR            2460 non-null   int64
 21  ORR           2460 non-null   int64
 22  DRR           2460 non-null   int64
 23  FT%           2460 non-null   float64
 24  TOV%          2460 non-null   float64
 25  EFG%          2460 non-null   float64
 26  DRB%          2460 non-null   float64
 27  ORB%          2460 non-null   float64
 28  DR            2460 non-null   int64
 29  TOT           2460 non-null   int64
 30  A             2460 non-null   int64
 31  PF            2460 non-null   int64
 32  ST            2460 non-null   int64
 33  TO            2460 non-null   int64
 34  BL            2460 non-null   int64
 35  PTS           2460 non-null   int64
 36  POSS          2460 non-null   float64
 37  PACE          2460 non-null   float64
 38  OEFF          2460 non-null   float64
 39  DEFF          2460 non-null   float64
 40  REST DAYS     2460 non-null   int64
 41  OPENING ODDS  2460 non-null   float64
 42  SPREAD        2460 non-null   float64
dtypes: float64(11), int64(29), object(3)
memory usage: 826.5+ KB

In [ ]:
#計算各欄位個數
data.count()

DATASET         2460
R/P             2460
DATE            2460
TEAMS           2460
H/R             2460
W/E             2460
W/L             2460
DIFF            2460
1Q              2460
2Q              2460
3Q              2460
4Q              2460
F               2460
MIN             2460
FG              2460
FGA             2460
3P              2460
3PA             2460
FT              2460
FTA             2460
OR              2460
ORR             2460
DRR             2460
FT%             2460
TOV%            2460
EFG%            2460
DRB%            2460
ORB%            2460
DR              2460
TOT             2460
A               2460
PF              2460
ST              2460
TO              2460
BL              2460
PTS             2460
POSS            2460
PACE            2460
OEFF            2460
DEFF            2460
REST DAYS       2460
OPENING ODDS    2460
SPREAD          2460
dtype: int64

# 單一數量資料分析：平均數、中位數、變異數、標準差

In [ ]:
#計算「PTS」欄位資料之平均數
data["PTS"].mean()

105.59024390243903

In [ ]:
#計算「PTS」欄位資料之中位數
data['PTS'].median()

106.0

In [ ]:
#計算「PTS」欄位資料之變異數
data["PTS"].var()

147.58559001775475

In [ ]:
#計算「PTS」欄位資料之標準差
data["PTS"].std()

12.148480975733335

In [ ]:
#計算「TO」欄位資料之平均數,取小數點到第二位
"%.2f"%data["TO"].mean()

'13.38'

In [ ]:
#計算所有欄位資料之平均數
data.mean()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

R/P               1.000000
H/R               1.500000
W/E               1.500000
W/L               0.500000
DIFF              0.000000
1Q               26.532927
2Q               26.548780
3Q               26.037805
4Q               25.772764
F               105.590650
MIN             241.626016
FG               39.049187
FGA              85.396748
3P                9.653659
3PA              26.997154
FT               17.838211
FTA              23.110976
OR               10.141463
ORR              10.141463
DRR              33.369106
FT%               0.211578
TOV%              0.122649
EFG%              0.515153
DRB%              0.768876
ORB%              0.231124
DR               33.369106
TOT              43.510569
A                22.626016
PF               19.898374
ST                7.712195
TO               13.378862
BL                4.758130
PTS             105.590244
POSS             97.017642
PACE             96.368780
OEFF            108.889756
DEFF            108.889756
REST DAYS         1.037398
OPENING ODDS    102.493902
SPREAD            0.000000
dtype: float64

In [ ]:
#計算所有欄位資料之描述性統計量
data.describe()

,R/P,H/R,W/E,W/L,DIFF,1Q,2Q,3Q,4Q,F,...,TO,BL,PTS,POSS,PACE,OEFF,DEFF,REST DAYS,OPENING ODDS,SPREAD
count,2460.0,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.00000,2460.000000,2460.000000,2460.000000,...,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000,2460.000000
mean,1.0,1.500000,1.500000,0.500000,0.000000,26.532927,26.54878,26.037805,25.772764,105.590650,...,13.378862,4.758130,105.590244,97.017642,96.368780,108.889756,108.889756,1.037398,102.493902,0.000000
std,0.0,0.500102,0.500102,0.500102,14.041158,5.836192,5.77366,5.893162,5.912538,12.148947,...,3.826711,2.475343,12.148481,5.642584,4.924046,11.382703,11.382703,0.735593,108.452662,6.829624
min,1.0,1.000000,1.000000,0.000000,-49.000000,8.000000,9.00000,8.000000,8.000000,64.000000,...,2.000000,0.000000,64.000000,82.000000,82.000000,71.800000,71.800000,0.000000,-22.000000,-22.000000
25%,1.0,1.000000,1.000000,0.000000,-9.000000,23.000000,23.00000,22.000000,22.000000,97.000000,...,11.000000,3.000000,97.000000,93.200000,92.900000,101.400000,101.400000,1.000000,-5.000000,-5.000000
50%,1.0,1.500000,1.500000,0.500000,0.000000,27.000000,27.00000,26.000000,26.000000,106.000000,...,13.000000,4.000000,106.000000,96.500000,96.100000,109.000000,109.000000,1.000000,90.000000,0.000000
75%,1.0,2.000000,2.000000,1.000000,9.000000,30.000000,30.00000,30.000000,30.000000,114.000000,...,16.000000,6.000000,114.000000,100.500000,99.800000,116.600000,116.600000,1.000000,210.500000,5.000000
max,1.0,2.000000,2.000000,1.000000,49.000000,47.000000,44.00000,50.000000,47.000000,149.000000,...,27.000000,15.000000,149.000000,130.800000,112.800000,147.200000,147.200000,3.000000,241.000000,22.000000

In [ ]:
#將所得的描述性統計量的統計陣列設為a
a = data.describe()

In [ ]:
#取描述性統計量的統計陣列中的兩個欄位「1Q」及「2Q」
a[['1Q','2Q']]

                1Q          2Q
count  2460.000000  2460.00000
mean     26.532927    26.54878
std       5.836192     5.77366
min       8.000000     9.00000
25%      23.000000    23.00000
50%      27.000000    27.00000
75%      30.000000    30.00000
max      47.000000    44.00000

In [ ]:
#DataFrame.loc
#Access a group of rows and columns by label(s) or a boolean array.
#取a陣列中兩個欄位「1Q」及「2Q」
a.loc[:, ["1Q","2Q"]]  #a.loc['mean', ["1Q","2Q"]]

                1Q          2Q
count  2460.000000  2460.00000
mean     26.532927    26.54878
std       5.836192     5.77366
min       8.000000     9.00000
25%      23.000000    23.00000
50%      27.000000    27.00000
75%      30.000000    30.00000
max      47.000000    44.00000

In [ ]:
#DataFrame.iloc
#Access group of rows and columns by integer position(s).
#取a陣列中第三行至第五行(編號2至4)
a.iloc[: , 2:5]

               W/E          W/L         DIFF
count  2460.000000  2460.000000  2460.000000
mean      1.500000     0.500000     0.000000
std       0.500102     0.500102    14.041158
min       1.000000     0.000000   -49.000000
25%       1.000000     0.000000    -9.000000
50%       1.500000     0.500000     0.000000
75%       2.000000     1.000000     9.000000
max       2.000000     1.000000    49.000000

In [ ]:
#取a陣列中編號1至編號2列＆編號5至編號6行的值
a.iloc[1:3, 5:7]

             1Q        2Q
mean  26.532927  26.54878
std    5.836192   5.77366

# Exercise:請計算「2019STA.xlsx」檔案中小考及期中考的平均數與標準差

In [ ]:
data1=pd.read_excel('2019STA.xlsx')
data1.head()

  Department Grade Gender  Quiz  Mid_Exam  Final_Exam
0         BA    一A      M    81      72.0          80
1         BA    一A      M    80      87.5          90
2         BA    一A      M    69      74.0          76
3         BA    一A      F    58      52.0          50
4         BA    一A      M    82      76.0          78

In [ ]:
a = data1.describe()

In [ ]:
a.loc[['mean','std'],['Quiz','Mid_Exam']]

           Quiz   Mid_Exam
mean  62.157895  61.991228
std   24.400519  24.797302

# 單一類別資料分析：次數分配與相對次數分配

In [ ]:
#使用groupby將資料以主客場分組(H/R)
f=data.groupby('H/R')
#用size()看f裡面每個組別內的大小
frequence=f.size()
#將frequence做成dataframe形式，並將資料columns命名為Frequence_主客場
flist=pd.DataFrame(frequence,columns=["Frequence_主客場"])
flist

     Frequence_主客場
H/R
1             1230
2             1230

In [ ]:
#使用groupby將資料以主客場分組(H/R)
f=data.groupby('H/R')
percentage=f.size()/len(data)
#將percentage做成dataframe形式，並將資料columns命名為Percentage_主客場
plist=pd.DataFrame(percentage,columns=["Percentage_主客場"])
plist

     Percentage_主客場
H/R
1               0.5
2               0.5

In [ ]:
#利用merge功能合併flist與plist兩個陣列
flist.merge(plist,on = 'H/R')

     Frequence_主客場  Percentage_主客場
H/R
1             1230             0.5
2             1230             0.5

In [ ]:
#想一次就列出下列三個變數:'H/R','W/E','W/L'的次數及相對次數分配表
a=['H/R','W/E','W/L']
for m in range(len(a)):
  f=data.groupby(a[m])
  percentage=f.size()/len(data)
  plist=pd.DataFrame(percentage,columns=["Percentage"])
  print(plist)

     Percentage
H/R
1           0.5
2           0.5
     Percentage
W/E
1           0.5
2           0.5
     Percentage
W/L
0           0.5
1           0.5

# Exercise:請計算「2019STA.xlsx」檔案中男女生比例

In [ ]:
f=data1.groupby('Gender')
percentage=f.size()/len(data1)
plist=pd.DataFrame(percentage,columns=["男女比例"])
plist

            男女比例
Gender
F       0.473684
M       0.526316

# 兩屬量變數分析：相關分析

方法一: 利用numpy之相關性corr相關分析的語法

In [ ]:
#計算3P及PTS的相關係數
import numpy as np
np.corrcoef(data["3P"],data["PTS"])

array([[1.        , 0.51042529],
       [0.51042529, 1.        ]])

In [ ]:
#同時想一次進行很多變數的相關分析
#量的資料
A=['DIFF', '1Q',
       '2Q', '3Q', '4Q', 'F', 'MIN', 'FG', 'FGA', '3P', '3PA', 'FT', 'FTA',
       'OR', 'ORR', 'DRR', 'FT%', 'TOV%', 'EFG%', 'DRB%', 'ORB%', 'DR', 'TOT',
       'A', 'PF', 'ST', 'TO', 'BL', 'PTS', 'POSS', 'PACE', 'OEFF', 'DEFF',
       'REST DAYS', 'OPENING ODDS', 'SPREAD']

方法二: 利用scipy之相關性corr相關分析的語法

In [ ]:
#計算PTS(總分)與其他變數的相關係數，並列出各變數之相關係數值
#皮爾森相關分析(量*量)
name=[]
alist=[]
for i in range(len(A)):
  (r,pv)=stats.pearsonr(data['PTS'],data[A[i]]) #(r, pv)，r為相關係數，pv為p-value
  name.append(A[i])
  alist.append(r)

In [ ]:
#資料結構以DataFrame顯示 
#語法:pd.DataFrame(資料,index名稱,columns名稱)
result=pd.DataFrame(alist,name,columns=['與PTS之相關係數'])
result

              與PTS之相關係數
DIFF           0.577876
1Q             0.506944
2Q             0.481409
3Q             0.503093
4Q             0.467508
F              0.999999
MIN            0.196595
FG             0.829357
FGA            0.265022
3P             0.510425
3PA            0.237998
FT             0.352147
FTA            0.307191
OR             0.002235
ORR            0.035799
DRR           -0.378457
FT%            0.267544
TOV%          -0.192517
EFG%           0.735735
DRB%           0.014873
ORB%           0.144737
DR             0.118143
TOT            0.099088
A              0.577553
PF             0.142519
ST             0.112034
TO            -0.106452
BL             0.075503
PTS            1.000000
POSS           0.428806
PACE           0.375827
OEFF           0.863989
DEFF           0.126544
REST DAYS      0.071114
OPENING ODDS  -0.195110
SPREAD        -0.259712

# Exercise:請計算「2019STA.xlsx」檔案中小考與期中考之相關性

In [ ]:
np.corrcoef(data1["Quiz"],data1["Mid_Exam"])

array([[1.        , 0.92144686],
       [0.92144686, 1.        ]])

# 兩類別變數分析：交叉分析

In [ ]:
#語法:pd.crosstab(rows,columns,margins=True)，margins=True表顯示all，False或不命令margins則不顯示
#請計算"W/L" VS "REST DAYS" 的交叉次數表
pd.crosstab(data["W/L"],data["REST DAYS"],margins=False)

REST DAYS    0    1    2   3
W/L
0          285  723  159  63
1          207  790  167  66

In [ ]:
#normalize=True是指每個cell除以總數所得的比例;normalize=0是指每個cell除以列的總數所得的比例;normalize=1是指每個cell除以行的總數所得的比例;
pd.crosstab(data["W/L"],data["REST DAYS"],margins=False, normalize=1)

REST DAYS         0         1        2         3
W/L
0          0.579268  0.477859  0.48773  0.488372
1          0.420732  0.522141  0.51227  0.511628

In [ ]:
#計算各球隊(TEAMS)在不同休息天數(REST DAYS)下勝場數(WL)之差異(利用groupby功能)
a=data.groupby(['TEAMS','REST DAYS']).sum()
a[["W/L"]]

                      W/L
TEAMS      REST DAYS
Atlanta    0           11
           1           23
           2            7
           3            2
Boston     0           10
...                   ...
Utah       3            5
Washington 0            7
           1           33
           2            8
           3            1

[120 rows x 1 columns]

# Exercise:請針對「2019STA.xlsx」檔案中的班級與性別進行交叉分析

In [ ]:
data1.head()

  Department Grade Gender  Quiz  Mid_Exam  Final_Exam
0         BA    一A      M    81      72.0          80
1         BA    一A      M    80      87.5          90
2         BA    一A      M    69      74.0          76
3         BA    一A      F    58      52.0          50
4         BA    一A      M    82      76.0          78

In [ ]:
pd.crosstab(data1["Department"],data1["Gender"],margins=False, normalize=0)

Gender             F         M
Department
BA          0.348837  0.651163
FM          0.857143  0.142857

# 兩變數：類別＊屬量變數分析：平均數之比較分析

In [ ]:
#利用groupby進行分群計算平均數
#計算勝場及負場的平均得分
a=data.groupby('W/L').mean()
b=a[['PTS']]
b

            PTS
W/L
0     99.929268
1    111.251220

In [ ]:
#利用groupby進行分群計算描述性統計量
b=data.groupby('W/L').describe()
b[['PTS']]

        PTS
      count        mean        std   min    25%    50%    75%    max
W/L
0    1230.0   99.929268  10.931209  64.0   93.0  100.0  107.0  139.0
1    1230.0  111.251220  10.566669  80.0  104.0  111.0  118.0  149.0

In [ ]:
#利用groupby進行分群計算東西區、主客場之平均數，
#請依東西區、主客場列出'PTS','TO','1Q','2Q','3Q','4Q'的平均數
a=data.groupby(['W/E','H/R']).mean()
a[['PTS','TO','1Q','2Q','3Q','4Q']]

                PTS         TO         1Q         2Q         3Q         4Q
W/E H/R
1   1    106.271545  13.164228  26.834146  26.639024  26.134959  25.899187
    2    103.346341  13.347967  25.928455  25.882927  25.323577  25.539837
2   1    108.058537  13.414634  27.317073  27.099187  26.920325  26.014634
    2    104.684553  13.588618  26.052033  26.573984  25.772358  25.637398

# Exercise:請針對「2019STA.xlsx」檔案中計算不同班級與不同性別之平均成績

In [ ]:
data1.head()

  Department Grade Gender  Quiz  Mid_Exam  Final_Exam
0         BA    一A      M    81      72.0          80
1         BA    一A      M    80      87.5          90
2         BA    一A      M    69      74.0          76
3         BA    一A      F    58      52.0          50
4         BA    一A      M    82      76.0          78

In [ ]:
a=data1.groupby(['Department','Gender']).mean()
a[['Quiz','Mid_Exam','Final_Exam']]

                        Quiz   Mid_Exam  Final_Exam
Department Gender
BA         F       69.333333  66.966667   67.600000
           M       51.607143  51.500000   60.035714
FM         F       73.416667  75.375000   78.166667
           M       88.500000  91.250000   89.000000