# 作業一：請針對所提供的資料檔案(boston_house(type).xlsx)進行以下分析：
1. 請計算此資料中房價的平均數、中位數、變異數與標準差。
2. 請計算此資料中房價超過20(PRICE TYPE=2)與低於20(PRICE TYPE=1)的個數及比例。
3. 請計算是否臨近Carles River(CHAS=0 or CHAS=1)地區房價之差異。
4. 請計算是否臨近Carles River(CHAS=0 or CHAS=1)地區房價高低之差異。
5. 請分析哪些量化因素與房價具有較高的關聯性？

備註：資料取自於Kaggle平台

In [ ]:
import pandas as pd
import numpy as np
from scipy import stats
data2=pd.read_excel('boston_house(type).xlsx')
data2.head()

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE,PRICE TYPE
0,0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0,2
1,1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6,2
2,2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7,2
3,3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4,2
4,4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2,2

In [ ]:
a=data2.describe()
a

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE,PRICE TYPE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,252.500000,3.593761,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806,1.575099
std,146.213884,8.596783,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104,0.494817
min,0.000000,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000,1.000000
25%,126.250000,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000,1.000000
50%,252.500000,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000,2.000000
75%,378.750000,3.647423,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000,2.000000
max,505.000000,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000,2.000000

第一題

請計算此資料中房價的平均數、中位數、變異數與標準差。

In [ ]:
print(a.loc[['mean','50%','std'],['PRICE']]) #50百分位數與中位數相同
print('var  ',data2['PRICE'].var())

          PRICE
mean  22.532806
50%   21.200000
std    9.197104
var   84.5867235940986

第二題

請計算此資料中房價超過20(PRICE TYPE=2)與低於20(PRICE TYPE=1)的個數及比例。

In [ ]:
f=data2.groupby('PRICE TYPE')
frequence=f.size()
flist=pd.DataFrame(frequence,columns=["個數"])

f=data2.groupby('PRICE TYPE')
percentage=f.size()/len(data2)
plist=pd.DataFrame(percentage,columns=["比例"])

flist.merge(plist,on = 'PRICE TYPE')

             個數        比例
PRICE TYPE
1           215  0.424901
2           291  0.575099

第三題

請計算是否臨近Carles River(CHAS=0 or CHAS=1)地區房價之差異。

In [ ]:
a=data2.groupby('CHAS').mean()
b=a[['PRICE']]
b

          PRICE
CHAS
0     22.093843
1     28.440000

第四題

請計算是否臨近Carles River(CHAS=0 or CHAS=1)地區房價高低之差異。

In [ ]:
pd.crosstab(data2["CHAS"],data2["PRICE TYPE"],margins=False, normalize=1)

PRICE TYPE         1         2
CHAS
0           0.962791  0.907216
1           0.037209  0.092784

In [ ]:
pd.crosstab(data2["CHAS"],data2["PRICE TYPE"],margins=False, normalize=0)

PRICE TYPE         1         2
CHAS
0           0.439490  0.560510
1           0.228571  0.771429

第五題

請分析哪些量化因素與房價具有較高的關聯性？

In [ ]:
data2.columns

Index(['Unnamed: 0', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE', 'PRICE TYPE'],
      dtype='object')

In [ ]:
A=['CRIM', 'ZN', 'INDUS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']

In [ ]:
name=[]
alist=[]
for i in range(len(A)):
  (r,pv)=stats.pearsonr(data2['PRICE'],data2[A[i]]) 
  name.append(A[i])
  alist.append(r)

In [ ]:
result=pd.DataFrame(alist,name,columns=['與PRICE之相關係數'])
result

         與PRICE之相關係數
CRIM       -0.385832
ZN          0.360445
INDUS      -0.483725
NOX        -0.427321
RM          0.695360
AGE        -0.376955
DIS         0.249929
RAD        -0.381626
TAX        -0.468536
PTRATIO    -0.507787
B           0.333461
LSTAT      -0.737663
PRICE       1.000000